### ISSUE TITLE
ARCHIVE REQUEST

### ISSUE THREAD

**Issue by Malix-off** [ahayzen/folderbox#10]
Hello!

Is this project still maintained ?

If not, it would perhaps make sense to archive it

**Comment by ahayzen** [comment]
Yup, it's used daily in production :-) I could probably add some more templates as I've got some other useful ones I use. But the sandboxes should still be working, if not report a bug!

**Comment by Malix-off** [comment]
> it's used daily in production

Nice to hear, do you have links ?

**Comment by ahayzen** [comment]
Not really, as "production" means using it on a developer machine to get a development environment you want for a project

**Comment by Malix-off** [comment]
Ohkay

Do you have any statistics / estimation about how much people are using it ?

**Comment by ahayzen** [comment]
Me at work for various customer and personal developer environments, beyond that I don't know :-) I have it here mainly in the hope it is useful for others even if it's just helping figuring out some of the sandbox escapes required for a certain thing to work

**Comment by Malix-off** [comment]
Cool thing, thanks !
